-- P14 of the 0409 unified plan (MIG-2): move a transfer's lane from its ITEMS to its HEADER,
-- settle the legacy APPROVED rows, and drop the superseded StockCount.location column.
--
-- ONE generated statement, four hand-written backfills. Everything additive was pre-paid by
-- MIG-1a on 5 Sep (every column this file writes already exists), so there is deliberately no
-- ADD COLUMN, CREATE INDEX, CREATE TYPE or ADD CONSTRAINT below. If `prisma migrate diff`
-- ever emits more than the single DROP COLUMN here, the schema has drifted -- stop and diff.
--
-- The one irreversible statement is `ALTER TABLE "StockCount" DROP COLUMN "location"`, and it
-- is legal under CLAUDE.md rule 7 ("drop only in the release AFTER the code stopped using
-- it") because:
--
--     * P6 removed every READER a release ago. `git grep` finds no expression reading it.
--     * The single surviving WRITER -- `src/app/api/stock-counts/route.ts`, which wrote
--       `location: null` -- is deleted in THIS commit, as rule 1 requires.
--
-- Dropping it without that code change would not be a runtime 500: `tsc` fails first, because
-- the field leaves StockCountCreateInput after `prisma generate`. But O11 runs migrate INSIDE
-- the Vercel build, so the column would already be gone and the build would then fail. The two
-- must travel together.
--
-- USES `IN_TRANSIT` / `RECEIVED`. Those values were added by MIG-1a, in an earlier
-- transaction. PostgreSQL forbids using an enum value added in the SAME transaction (55P04),
-- which is the entire reason this is a third folder rather than an edit to MIG-1a -- and
-- editing a merged migration is forbidden anyway (CLAUDE.md rule 6).
--
-- Prisma has no down migrations. The rollback is the snapshot taken before merge
-- (`npm run db:snapshot`, CLAUDE.md rule 9).

-- AlterTable
ALTER TABLE "StockCount" DROP COLUMN "location";

-- ------------------------------------------------------------------------------------------
-- HAND-WRITTEN BACKFILLS. Everything above this line was generated by `prisma migrate diff`
-- and read line by line; everything below was added by hand and is not reproducible from the
-- schema. All four are idempotent and all four are no-ops on a database that has no such rows.
--
--     SELECT count(*) FROM "TransferOrder";                          ->  0
--     SELECT count(*) FROM "TransferOrderItem";                      ->  0
--     -- orders whose items disagree about the lane:                 ->  0
--     SELECT count(*) FROM (SELECT "transferOrderId" FROM "TransferOrderItem"
--       GROUP BY "transferOrderId"
--       HAVING count(DISTINCT "fromWarehouseId") > 1
--           OR count(DISTINCT "toWarehouseId") > 1) t;
--                                                (all checked on bch-local, 7 Sep 2026)
--
-- Zero rows locally means these are UNTESTED against real data (CLAUDE.md rule 10 asks for a
-- production restore; plan §10 BL6 is still open). They are written to be safe on an empty
-- table and correct on a populated one, and every one of them is re-runnable.
-- ------------------------------------------------------------------------------------------

-- 1. HEADER LANE, from the items that carry it today.
--
-- Only orders whose items AGREE on a single from/to pair are backfilled -- `min() = max()` is
-- the agreement test. An order with genuinely mixed lanes cannot be represented on a header
-- and is deliberately LEFT NULL rather than silently collapsed to one of its lanes; P14's
-- detail route falls back to the item lane when the header is null, so such an order stays
-- readable. No such order exists locally, and the create route has always written one lane per
-- order, so this is a guard against data we do not believe exists rather than an expected case.
UPDATE "TransferOrder" o
SET "fromWarehouseId" = agreed."fromId",
    "toWarehouseId"   = agreed."toId"
FROM (
  SELECT "transferOrderId",
         min("fromWarehouseId") AS "fromId",
         min("toWarehouseId")   AS "toId"
  FROM "TransferOrderItem"
  WHERE "fromWarehouseId" IS NOT NULL
    AND "toWarehouseId"   IS NOT NULL
  GROUP BY "transferOrderId"
  HAVING min("fromWarehouseId") = max("fromWarehouseId")
     AND min("toWarehouseId")   = max("toWarehouseId")
) agreed
WHERE o.id = agreed."transferOrderId"
  AND o."fromWarehouseId" IS NULL;

-- 2. TRANSFER TYPE, derived from the two stores now that the header carries the lane.
--
-- `requiredDocType` is deliberately NOT set. A NULL there means "raised before the document
-- policy existed", and P15's dispatch gate skips the document check for exactly those rows.
-- Deriving one retrospectively would invent a compliance record for a movement that has
-- already physically happened -- and worse, an INTER_STORE row would need a tax invoice
-- nobody ever raised, permanently blocking an order that is otherwise finished.
UPDATE "TransferOrder" o
SET "transferType" = CASE
      WHEN fw."storeId" = tw."storeId" THEN 'INTRA_STORE'::"TransferType"
      ELSE 'INTER_STORE'::"TransferType"
    END
FROM "Warehouse" fw, "Warehouse" tw
WHERE o."fromWarehouseId" = fw.id
  AND o."toWarehouseId"   = tw.id
  AND o."transferType" IS NULL;

-- 3. LEGACY APPROVED ORDERS BECOME RECEIVED. This is the load-bearing one.
--
-- Under the OLD code, approving a transfer moved the stock immediately -- source and
-- destination were both written inside the approve route. Under P14, APPROVED means "agreed,
-- nothing has moved yet" and the movement happens at dispatch.
--
-- So an APPROVED row left alone after this deploy is a trap: its stock has ALREADY moved, and
-- the new Dispatch button would happily deduct it a SECOND time. Reading them as RECEIVED is
-- what makes the old rows agree with the new meaning -- the goods did leave, and they did
-- arrive, both at approval time. `reviewedAt` is the only timestamp those rows have, so it
-- stands in for both dispatch and receipt, and `reviewedById` for both actors.
--
-- REJECTED, CANCELLED and PENDING rows are untouched: none of them ever moved stock.
UPDATE "TransferOrder"
SET status           = 'RECEIVED'::"TransferOrderStatus",
    "dispatchedAt"   = COALESCE("dispatchedAt", "reviewedAt"),
    "dispatchedById" = COALESCE("dispatchedById", "reviewedById"),
    "receivedAt"     = COALESCE("receivedAt", "reviewedAt"),
    "receivedById"   = COALESCE("receivedById", "reviewedById"),
    "receiveNote"    = COALESCE("receiveNote", 'Received on approval, before the in-transit flow existed (MIG-2).')
WHERE status = 'APPROVED'::"TransferOrderStatus";

-- 4. RECEIVED QUANTITIES for those same legacy rows.
--
-- The old flow had no concept of a short receipt: whatever was approved was what moved. So
-- `receivedQty = quantity` is the honest reading, and it is what stops the detail screen
-- showing every historical line as a total shortfall.
--
-- NULL means "not received yet" and 0 means "received, none arrived" -- so this must only ever
-- fill NULLs, never overwrite a real 0. Hence the IS NULL.
UPDATE "TransferOrderItem" i
SET "receivedQty" = i.quantity
FROM "TransferOrder" o
WHERE i."transferOrderId" = o.id
  AND o.status = 'RECEIVED'::"TransferOrderStatus"
  AND i."receivedQty" IS NULL;
